name: ETL Apuestas Diario

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests scipy

      - name: Ejecutar motor de extracción
        run: python updater.py
        env:
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}

      - name: Guardar la nueva base de datos
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Matches.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualizacion automatica: Partidos nuevos" && git push)
